swagger: "2.0"
info:
  description: User
  version: "1.0.0"
  title: API-User
host: api.tensquare.com
basePath: /tensquare_user
paths:
  /user:
    post:
      summary: 增加User
      parameters:
      - in: body
        name: body
        description: User实体
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: User全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiUserListResponse'
  /user/{userId}:
    get:
      summary: 根据ID查询user
      parameters:
        - name: userId
          in: path
          description: UserID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiUserResponse'
    put:
      summary: 修改User
      parameters:
        - name: userId
          in: path
          description: UserID
          required: true
          type: string
        - name: body
          in: body
          description: User实体
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除User
      parameters:
        - name: userId
          in: path
          description: UserID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/search:
    post:
      summary: 根据条件查询User列表 
      parameters:
        - name: body
          in: body
          description: User实体类
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiUserListResponse'
  /user/search/{page}/{size}:
    post:
      summary: User分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiUserPageResponse'
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "string"        
        description: "ID"
      loginname:
        type: "string"        
        description: "登录名"
      mobile:
        type: "string"        
        description: "手机号码"
      password:
        type: "string"        
        description: "密码"
      nickname:
        type: "string"        
        description: "昵称"
      sex:
        type: "string"        
        description: "性别"
      birthday:
        type: "string"        
        description: "出生年月日"
      avatar:
        type: "string"        
        description: "头像"
      email:
        type: "string"        
        description: "E-Mail"
      regdate:
        type: "string"        
        description: "注册日期"
      updatedate:
        type: "string"        
        description: "修改日期"
      lastdate:
        type: "string"        
        description: "最后登陆日期"
      online:
        type: "string"        
        description: "在线时长（分钟）"
      interest:
        type: "string"        
        description: "兴趣"
      image:
        type: "string"        
        description: "头像"
      personality:
        type: "string"        
        description: "个性"
      fanscount:
        type: "string"        
        description: "粉丝数"
      followcount:
        type: "string"        
        description: "关注数"

  UserList:
    type: "array"
    items: 
      $ref: '#/definitions/User'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiUserResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/User'
  ApiUserListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/UserList'
  ApiUserPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/UserList'
